---
- name: Configure NFS mounts in /etc/fstab
  hosts: all
  become: true
  vars:
    host_ip: "192.168.56.116"  # Replace with the appropriate host IP

  tasks:
    - name: Edit /etc/fstab
      command: "echo -e '{{ item }}' | sudo tee -a /etc/fstab"
      with_items:
        - "{{ host_ip }}:/var/nfs/general    /nfs/general   nfs auto,nofail,noatime,nolock,intr,tcp,actimeo=1800 0 0"
        - "{{ host_ip }}:/home               /nfs/home      nfs auto,nofail,noatime,nolock,intr,tcp,actimeo=1800 0 0"

    - name: Verify /etc/fstab changes
      command: mount -a
      become_method: sudo

