---
- name: Remove Docker installation
  hosts: all
  become: yes

  tasks:
    - name: Stop Docker service
      service:
        name: docker
        state: stopped

    - name: Uninstall Docker
      apt:
        name: docker-ce, docker-ce-cli, containerd.io
        state: absent
      when: ansible_pkg_mgr == 'apt'  # Modify for Ubuntu/Debian

    - name: Uninstall Docker
      yum:
        name: docker-ce, docker-ce-cli, containerd.io
        state: absent
      when: ansible_pkg_mgr == 'yum'  # Modify for CentOS/Fedora

    - name: Remove Docker directories
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /var/lib/docker
        - /etc/docker

