---
- name: Install nfs-common
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_pkg_mgr == 'apt'

    - name: Install nfs-common package
      package:
        name: nfs-common
        state: present

